/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuh_sotest3_Hello */

#ifndef _Included_com_liuh_sotest3_Hello
#define _Included_com_liuh_sotest3_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuh_sotest3_Hello
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_liuh_sotest3_Hello_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
